excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Example/Tests/MockJSON.swift
  - Example/Pods
  # - Carthage
  - Pods

disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - force_cast
